<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0-browserwasm;net10.0-desktop</TargetFrameworks>
    <UnoSingleProject>true</UnoSingleProject>
    <OutputType>Exe</OutputType>
    <UnoFeatures>SkiaRenderer;</UnoFeatures>
    <ApplicationTitle>DataSpace</ApplicationTitle>
    <ApplicationId>org.dataspace.app</ApplicationId>
    <ApplicationDisplayVersion>0.2.0</ApplicationDisplayVersion>
    <ApplicationVersion>3</ApplicationVersion>
    <IsPackable>false</IsPackable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <WasmShellWebAppBasePath>./</WasmShellWebAppBasePath>
    <WasmShellEnableThreads>false</WasmShellEnableThreads>
    <RunAOTCompilation>false</RunAOTCompilation>
    <WasmShellAppTitle>DataSpace</WasmShellAppTitle>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DataSpace.Controls/DataSpace.Controls.csproj" />
    <Content Include="browser-storage.js" UnoDeploy="Root" />
  </ItemGroup>
</Project>
